# Generated by Django 5.0 on 2024-01-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmfaxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_of_fax', models.CharField(max_length=255)),
                ('fax_entry_time', models.CharField(max_length=255)),
                ('authenticity_verification', models.CharField(max_length=255)),
                ('visual_signal', models.BooleanField(default=False)),
                ('acoustic_signal', models.BooleanField(default=False)),
                ('signal_audible', models.BooleanField(default=False)),
                ('reason_not_audible', models.CharField(blank=True, max_length=255)),
                ('signal_description', models.TextField()),
                ('signal_visible', models.BooleanField(default=False)),
                ('reason_not_visible', models.CharField(blank=True, max_length=255)),
                ('signal_description_always', models.TextField()),
                ('areas_where_signal_is_seen_or_heard', models.TextField()),
                ('person_receiving_alarm', models.CharField(max_length=255)),
                ('decision_and_actions', models.TextField()),
                ('information_passed_to', models.JSONField()),
                ('additional_information', models.TextField()),
                ('red_phone_location', models.CharField(max_length=255)),
                ('is_phone_monitored', models.BooleanField(default=False)),
                ('by_whom', models.CharField(blank=True, max_length=255)),
                ('how_is_it_monitored', models.CharField(blank=True, max_length=255)),
                ('alarm_assignment', models.CharField(max_length=255)),
                ('internal_alarm_system', models.CharField(max_length=255)),
                ('external_alarm_system', models.CharField(max_length=255)),
                ('internal_fallback', models.TextField()),
                ('external_fallback', models.TextField()),
            ],
        ),
    ]
