# Generated by Django 5.0 on 2024-01-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmfaxmodel',
            old_name='acoustic_signal',
            new_name='frage5Akustisch',
        ),
        migrations.RenameField(
            model_name='alarmfaxmodel',
            old_name='is_phone_monitored',
            new_name='frage5Optisch',
        ),
        migrations.RenameField(
            model_name='alarmfaxmodel',
            old_name='signal_audible',
            new_name='isPhoneMonitored',
        ),
        migrations.RenameField(
            model_name='alarmfaxmodel',
            old_name='signal_visible',
            new_name='signalAudible',
        ),
        migrations.RenameField(
            model_name='alarmfaxmodel',
            old_name='visual_signal',
            new_name='signalVisible',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='alarm_assignment',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='areas_where_signal_is_seen_or_heard',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='authenticity_verification',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='by_whom',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='decision_and_actions',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='external_alarm_system',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='external_fallback',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='fax_entry_time',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='how_is_it_monitored',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='information_passed_to',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='internal_alarm_system',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='internal_fallback',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='location_of_fax',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='person_receiving_alarm',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='reason_not_audible',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='reason_not_visible',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='red_phone_location',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='signal_description',
        ),
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='signal_description_always',
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='additionalInformation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='alarmAssignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='areasWhereSignalIsSeenOrHeard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='byWhom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='decisionAndActions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='externalAlarmSystem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='externalFallback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='frage1Input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='frage2Input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='frage3Input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='howIsItMonitored',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='informationPassedTo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='internalAlarmSystem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='internalFallback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='personReceivingAlarm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='reasonNotAudible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='reasonNotVisible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='redPhoneLocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='signalDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='signalDescriptionAlways',
            field=models.TextField(blank=True, null=True),
        ),
    ]
