# Generated by Django 5.0.1 on 2024-01-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0004_alarmfaxmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='image',
        ),
        migrations.CreateModel(
            name='AlarmfaxImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alarmfax_images/')),
                ('alarmfax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DUEBapp.alarmfaxmodel')),
            ],
        ),
    ]
