# Generated by Django 5.0.1 on 2024-01-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0005_remove_alarmfaxmodel_image_alarmfaximage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='alarmfaximage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alarmfax_images/'),
        ),
    ]
