# Generated by Django 5.0.1 on 2024-01-10 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0006_alarmfaxmodel_image_alter_alarmfaximage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmfaximage',
            name='alarmfax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DUEBapp.alarmfaxmodel'),
        ),
    ]
