# Generated by Django 5.0.1 on 2024-01-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0007_alter_alarmfaximage_alarmfax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmfaximage',
            name='alarmfax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DUEBapp.alarmfaxmodel'),
        ),
    ]
