# Generated by Django 5.0.1 on 2024-01-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0008_alter_alarmfaximage_alarmfax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='image',
        ),
    ]
