# Generated by Django 5.0.1 on 2024-01-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0010_imagemodel_delete_alarmfaximage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alarmfax_images/'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
