# Generated by Django 5.0.1 on 2024-01-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0011_alarmfaxmodel_image_delete_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmfaxmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='alarmfaxmodel',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
