# Generated by Django 5.0.1 on 2024-03-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0015_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='type',
        ),
    ]
