# Generated by Django 5.0.1 on 2024-03-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0016_remove_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_upload_desired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_type',
            field=models.CharField(choices=[('none', 'None'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('scale', 'Scale'), ('image', 'Image')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
