# Generated by Django 5.0.1 on 2024-03-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0017_question_image_upload_desired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
