# Generated by Django 5.0.1 on 2024-03-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0018_form_description_question_hint_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='description',
            new_name='description_form',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='hint_text',
            new_name='description_question',
        ),
    ]
