# Generated by Django 5.0.1 on 2024-03-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0019_rename_description_form_description_form_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlarmfaxModel',
        ),
    ]
