# Generated by Django 5.0.1 on 2024-04-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0022_formresponse_response_responseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='form_response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='responseimage',
            name='response',
        ),
        migrations.DeleteModel(
            name='FormResponse',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='ResponseImage',
        ),
    ]
