# Generated by Django 5.0.1 on 2024-05-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0023_remove_response_form_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
