# Generated by Django 5.0.1 on 2024-10-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0024_form_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_name', models.CharField(blank=True, max_length=255)),
                ('observer_email', models.CharField(blank=True, max_length=255)),
                ('responses', models.JSONField()),
                ('picker_selections', models.JSONField(blank=True, null=True)),
                ('scale_values', models.JSONField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('timestamps', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='DUEBapp.form')),
            ],
        ),
    ]
