# Generated by Django 5.0.1 on 2024-11-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0027_formresponse_image_11_formresponse_image_12_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreenContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homescreen/')),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
