# Generated by Django 5.0.1 on 2024-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0028_homescreencontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('general_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeScreenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homescreen/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='homescreencontent',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='homescreencontent',
            name='image',
        ),
        migrations.AddField(
            model_name='homescreencontent',
            name='contacts',
            field=models.ManyToManyField(related_name='home_screen_contents', to='DUEBapp.contact'),
        ),
        migrations.AddField(
            model_name='homescreencontent',
            name='images',
            field=models.ManyToManyField(related_name='home_screen_contents', to='DUEBapp.homescreenimage'),
        ),
    ]
