# Generated by Django 5.0.1 on 2024-12-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0029_contact_homescreenimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeScreenContent',
        ),
    ]
