# Generated by Django 5.0.1 on 2025-01-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0032_excelupload_victimprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(help_text="z.B. 'J' für Johanniter", max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='actor_hints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='anesthesia_team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='birthdate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='blood_units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='e_fast',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='ekg_monitor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='emergency_op',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='expected_med_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='fast_sono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='gcs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='hb_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='icu_place',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='op_achi_res',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='op_nchi_res',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='op_sieve_basic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='op_sieve_special',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='op_uchi_res',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='pcz_ivena',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='personal_resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='pre_treatment_rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='radiology_finds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='radiology_resources',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='red_treatment_area',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='rekap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='required_specialty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='resp_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='ro_thorax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='scenario_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='spo2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='sys_rr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='ventilation_place',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='visual_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScenarioAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_number', models.PositiveIntegerField()),
                ('button_number', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DUEBapp.organization')),
                ('victim_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DUEBapp.victimprofile')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='DUEBapp.testscenario')),
            ],
        ),
    ]
