# Generated by Django 5.0.1 on 2025-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0033_organization_testscenario_victimprofile_actor_hints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='short_code',
            field=models.CharField(help_text="z.B. 'J'", max_length=10, unique=True),
        ),
    ]
