# Generated by Django 5.0.1 on 2025-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0035_update_scenario_assignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scenarioassignment',
            constraint=models.UniqueConstraint(fields=('scenario', 'victim_profile'), name='unique_scenario_profile'),
        ),
        migrations.AddConstraint(
            model_name='scenarioassignment',
            constraint=models.UniqueConstraint(fields=('scenario', 'sequential_number'), name='unique_scenario_number'),
        ),
        migrations.AddConstraint(
            model_name='scenarioassignment',
            constraint=models.UniqueConstraint(fields=('scenario', 'button_number'), name='unique_scenario_button'),
        ),
    ]
