# Generated by Django 5.0.1 on 2025-01-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0036_add_scenario_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioassignment',
            name='organization',
        ),
        migrations.AddField(
            model_name='testscenario',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DUEBapp.organization'),
        ),
    ]
