# Generated by Django 5.0.1 on 2025-01-21 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0037_remove_scenarioassignment_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testscenario',
            name='organization',
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TestScenarioVictim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_number', models.PositiveIntegerField()),
                ('button_number', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DUEBapp.organization')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='DUEBapp.testscenario')),
                ('victim_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DUEBapp.victimprofile')),
            ],
            options={
                'ordering': ['sequential_number'],
            },
        ),
        migrations.AddField(
            model_name='testscenario',
            name='selected_profiles',
            field=models.ManyToManyField(related_name='scenarios', through='DUEBapp.TestScenarioVictim', to='DUEBapp.victimprofile'),
        ),
        migrations.DeleteModel(
            name='ScenarioAssignment',
        ),
        migrations.AddConstraint(
            model_name='testscenariovictim',
            constraint=models.UniqueConstraint(fields=('scenario', 'victim_profile'), name='unique_scenario_profile'),
        ),
        migrations.AddConstraint(
            model_name='testscenariovictim',
            constraint=models.UniqueConstraint(fields=('scenario', 'sequential_number'), name='unique_scenario_number'),
        ),
        migrations.AddConstraint(
            model_name='testscenariovictim',
            constraint=models.UniqueConstraint(fields=('scenario', 'button_number'), name='unique_scenario_button'),
        ),
    ]
