# Generated by Django 5.0.1 on 2025-01-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0039_alter_contact_options_alter_excelupload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='victimprofile',
            name='spare_col1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Leere Spalte 1 (AK)'),
        ),
        migrations.AddField(
            model_name='victimprofile',
            name='spare_col2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Leere Spalte 2 (AL)'),
        ),
    ]
