# Generated by Django 5.0.1 on 2025-02-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0040_victimprofile_spare_col1_victimprofile_spare_col2'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='show_patient_profile_search',
            field=models.BooleanField(default=False, verbose_name='Patientenprofil-Suche anzeigen'),
        ),
    ]
