# Generated by Django 5.0.1 on 2025-02-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0041_form_show_patient_profile_search'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testscenariovictim',
            name='unique_scenario_number',
        ),
        migrations.AddConstraint(
            model_name='testscenariovictim',
            constraint=models.UniqueConstraint(fields=('scenario', 'organization', 'sequential_number'), name='unique_scenario_org_number'),
        ),
    ]
