# Generated by Django 5.0.1 on 2025-02-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0042_remove_testscenariovictim_unique_scenario_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testscenariovictim',
            name='unique_scenario_profile',
        ),
    ]
