# Generated by Django 5.0.1 on 2025-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0043_remove_testscenariovictim_unique_scenario_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='access_code',
        ),
        migrations.CreateModel(
            name='ObserverAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Benutzername')),
                ('first_name', models.CharField(max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('password', models.CharField(max_length=128, verbose_name='Passwort')),
                ('show_patient_profiles', models.BooleanField(default=False, verbose_name='Patientenprofile anzeigen')),
                ('allowed_forms', models.ManyToManyField(blank=True, to='DUEBapp.form', verbose_name='Zugängliche Formulare')),
            ],
            options={
                'verbose_name': 'Beobachterkonto',
                'verbose_name_plural': 'Beobachterkonten',
            },
        ),
    ]
