# Generated by Django 5.0.1 on 2025-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0044_remove_form_access_code_observeraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VictimProfileResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_number', models.CharField(max_length=50, verbose_name='Button-Nr')),
                ('kh_intern', models.CharField(blank=True, max_length=50, null=True, verbose_name='KH interne Pat.-Nr')),
                ('soll_sichtung', models.CharField(blank=True, max_length=100, null=True, verbose_name='SOLL-Sichtungskategorie')),
                ('diagnostic_loaded', models.JSONField(blank=True, null=True, verbose_name='Diagnostische Angaben (SOLL)')),
                ('vitalwerte', models.JSONField(blank=True, null=True, verbose_name='Vitalparameter (SOLL)')),
                ('ist_sichtung', models.CharField(blank=True, max_length=100, null=True, verbose_name='IST-Sichtungskategorie')),
                ('sichtung_data', models.JSONField(blank=True, null=True, verbose_name='Sichtungspunkt-Daten')),
                ('diagnostik_data', models.JSONField(blank=True, null=True, verbose_name='Diagnostik-Daten')),
                ('therapie_data', models.JSONField(blank=True, null=True, verbose_name='Therapie-Daten')),
                ('op_team', models.JSONField(blank=True, null=True, verbose_name='OP-Team')),
                ('verlauf', models.JSONField(blank=True, null=True, verbose_name='Verlaufseinträge')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
        ),
    ]
