# Generated by Django 5.0.1 on 2025-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0045_victimprofileresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victimprofileresponse',
            options={'verbose_name': 'Antwort Patientenbegleitbogen', 'verbose_name_plural': 'Antworten Patientenbegleitbogen'},
        ),
        migrations.AddField(
            model_name='victimprofileresponse',
            name='observer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Beobachter-Email'),
        ),
        migrations.AddField(
            model_name='victimprofileresponse',
            name='observer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beobachter-Name'),
        ),
    ]
