# Generated by Django 5.0.1 on 2025-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0046_alter_victimprofileresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victimprofileresponse',
            options={'ordering': ['-erstellt_am'], 'verbose_name': 'Antwort Patientenbegleitbogen', 'verbose_name_plural': 'Antworten Patientenbegleitbogen'},
        ),
        migrations.AddField(
            model_name='victimprofileresponse',
            name='aktualisiert_am',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='victimprofileresponse',
            name='op_team',
            field=models.JSONField(blank=True, help_text='Liste der OP-Team-Einträge (max. 10)', null=True, verbose_name='OP-Team'),
        ),
        migrations.AlterField(
            model_name='victimprofileresponse',
            name='verlauf',
            field=models.JSONField(blank=True, help_text='Liste der Verlaufseinträge (max. 10)', null=True, verbose_name='Verlaufseinträge'),
        ),
    ]
