# Generated by Django 5.0.1 on 2025-03-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0047_alter_victimprofileresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimprofileresponse',
            name='verlauf',
            field=models.JSONField(blank=True, help_text='Verlaufseinträge und Kommentare', null=True, verbose_name='Verlaufseinträge'),
        ),
    ]
