# Generated by Django 5.0.1 on 2025-03-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0048_alter_victimprofileresponse_verlauf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimprofileresponse',
            name='verlauf',
            field=models.JSONField(blank=True, help_text='Liste der Verlaufseinträge (max. 10)', null=True, verbose_name='Verlaufseinträge'),
        ),
    ]
