# Generated by Django 5.0.1 on 2025-05-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0049_alter_victimprofileresponse_verlauf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Zugangsdaten für die DÜB-Übung', max_length=100, verbose_name='Betreff')),
                ('email_text', models.TextField(default='Sehr geehrte(r) {name},\n\nhiermit erhalten Sie Ihre Zugangsdaten für die digitale Übungsbeobachtung (DÜB):\n\nBenutzername: {username}\nPasswort: {password}\n\nBitte melden Sie sich mit diesen Daten in der DÜB-App an.\n\nMit freundlichen Grüßen,\nIhr DÜB-Team', verbose_name='E-Mail-Text')),
                ('selected_observers', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'E-Mail-Konfiguration',
                'verbose_name_plural': 'E-Mail-Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='ObserverNotification',
            fields=[
            ],
            options={
                'verbose_name': 'Beobachter-Benachrichtigung',
                'verbose_name_plural': 'Beobachter-Benachrichtigungen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('DUEBapp.observeraccount',),
        ),
    ]
