# Generated by Django 5.0.1 on 2025-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0050_emailconfig_observernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfig',
            name='selected_observers',
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='selected_observers',
            field=models.ManyToManyField(blank=True, to='DUEBapp.observeraccount', verbose_name='Ausgewählte Beobachter'),
        ),
    ]
