# Generated by Django 5.0.1 on 2025-06-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0051_remove_emailconfig_selected_observers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Excel-Upload', 'verbose_name_plural': 'Excel-Uploads'},
        ),
        migrations.AddField(
            model_name='excelupload',
            name='end_row',
            field=models.PositiveIntegerField(blank=True, help_text='Bis zu welcher Zeile importieren? (Leer = automatisch bis Ende)', null=True, verbose_name='End-Zeile'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='header_row',
            field=models.PositiveIntegerField(default=1, help_text='In welcher Zeile stehen die Spalten-Überschriften?', verbose_name='Header-Zeile'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='import_log',
            field=models.TextField(blank=True, null=True, verbose_name='Import-Protokoll'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='last_import_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzter Import'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='rows_failed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fehlgeschlagene Zeilen'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='rows_imported',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Importierte Zeilen'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='rows_updated',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aktualisierte Zeilen'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='skip_empty_rows',
            field=models.BooleanField(default=True, verbose_name='Leere Zeilen überspringen'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='start_row',
            field=models.PositiveIntegerField(default=2, help_text='Ab welcher Zeile soll importiert werden? (Standard: 2, da Zeile 1 meist Header)', verbose_name='Start-Zeile'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Hochgeladen'), ('configured', 'Konfiguriert'), ('imported', 'Importiert'), ('error', 'Fehler')], default='uploaded', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='total_rows_detected',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Erkannte Zeilen'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='update_existing',
            field=models.BooleanField(default=True, help_text='Sollen bestehende Profile (gleiche profile_number) aktualisiert werden?', verbose_name='Bestehende Profile aktualisieren'),
        ),
        migrations.CreateModel(
            name='ExcelColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_column_index', models.PositiveIntegerField(help_text='0-basierter Index (A=0, B=1, etc.)', verbose_name='Excel-Spalten-Index')),
                ('excel_column_letter', models.CharField(help_text='z.B. A, B, C, AA, etc.', max_length=5, verbose_name='Excel-Spalten-Buchstabe')),
                ('excel_header_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Excel-Header')),
                ('victim_profile_field', models.CharField(blank=True, choices=[], help_text='Welchem VictimProfile-Feld soll diese Spalte zugeordnet werden?', max_length=100, null=True, verbose_name='VictimProfile-Feld')),
                ('custom_field_name', models.CharField(blank=True, help_text='Optional: Anderer Name für diese Spalte verwenden', max_length=255, null=True, verbose_name='Eigener Feldname')),
                ('is_active', models.BooleanField(default=True, help_text='Soll diese Spalte importiert werden?', verbose_name='Aktiv')),
                ('is_required', models.BooleanField(default=False, help_text='Ist diese Spalte ein Pflichtfeld?', verbose_name='Pflichtfeld')),
                ('sample_values', models.JSONField(blank=True, help_text='Die ersten 5 Werte aus dieser Spalte zur Vorschau', null=True, verbose_name='Beispiel-Werte')),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Zahl'), ('date', 'Datum'), ('boolean', 'Ja/Nein')], default='text', max_length=20, verbose_name='Datentyp')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('excel_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='DUEBapp.excelupload', verbose_name='Excel-Upload')),
            ],
            options={
                'verbose_name': 'Excel-Spalten-Zuordnung',
                'verbose_name_plural': 'Excel-Spalten-Zuordnungen',
                'ordering': ['order', 'excel_column_index'],
                'unique_together': {('excel_upload', 'excel_column_index')},
            },
        ),
    ]
