# Generated by Django 5.0.1 on 2025-06-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0052_alter_excelupload_options_excelupload_end_row_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelupload',
            options={'verbose_name': 'Excel-Upload', 'verbose_name_plural': 'Excel-Uploads'},
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='end_row',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='header_row',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='import_log',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='last_import_at',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='rows_failed',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='rows_imported',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='rows_updated',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='skip_empty_rows',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='start_row',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='status',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='total_rows_detected',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='update_existing',
        ),
        migrations.DeleteModel(
            name='ExcelColumnMapping',
        ),
    ]
