# Generated by Django 5.0.1 on 2025-06-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0053_alter_excelupload_options_remove_excelupload_end_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimprofile',
            name='spare_col1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hinweis 1 für HiO'),
        ),
        migrations.AlterField(
            model_name='victimprofile',
            name='spare_col2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hinweis 2 für HiO'),
        ),
    ]
