# Generated by Django 4.2.27 on 2026-01-05 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0054_alter_victimprofile_spare_col1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='test_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to='DUEBapp.testscenario', verbose_name='Testszenario'),
        ),
        migrations.AddField(
            model_name='victimprofileresponse',
            name='test_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victim_profile_responses', to='DUEBapp.testscenario', verbose_name='Testszenario'),
        ),
    ]
