# Generated by Django 4.2.27 on 2026-01-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0055_formresponse_test_scenario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimprofile',
            name='emergency_op',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Not-OP [J/N]'),
        ),
        migrations.AlterField(
            model_name='victimprofile',
            name='icu_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ITS-Platz [J/N]'),
        ),
        migrations.AlterField(
            model_name='victimprofile',
            name='red_treatment_area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Roter Behandlungsbereich [J/N]'),
        ),
        migrations.AlterField(
            model_name='victimprofile',
            name='ventilation_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beatmungsplatz [J/N]'),
        ),
    ]
