# Generated by Django 4.2.28 on 2026-03-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0056_alter_victimprofile_emergency_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='email_text',
            field=models.TextField(default='Sehr geehrte(r) {name},\n\nhiermit erhalten Sie Ihre Zugangsdaten für die digitale Übungsbeobachtung (DÜB):\n\nBenutzername: {username}\nPasswort: {password}\n\nBitte melden Sie sich unter folgendem Link an:\n{login_url}\n\nSie können dort während und nach der Übung Ihre Beobachtungen bearbeiten.\n\nMit freundlichen Grüßen,\nIhr DÜB-Team', verbose_name='E-Mail-Text'),
        ),
        migrations.CreateModel(
            name='CompletedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_email', models.EmailField(max_length=254, verbose_name='Beobachter-Email')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Abgeschlossen')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DUEBapp.form', verbose_name='Formular')),
            ],
            options={
                'verbose_name': 'Abgeschlossenes Formular',
                'verbose_name_plural': 'Abgeschlossene Formulare',
                'unique_together': {('form', 'observer_email')},
            },
        ),
    ]
