# Generated by Django 4.2.28 on 2026-03-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0057_alter_emailconfig_email_text_completedform'),
    ]

    operations = [
        migrations.AddField(
            model_name='victimprofileresponse',
            name='diagnostik_locked',
            field=models.BooleanField(default=False, verbose_name='Diagnostik gesperrt'),
        ),
        migrations.AddField(
            model_name='victimprofileresponse',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Abgeschlossen'),
        ),
        migrations.AddField(
            model_name='victimprofileresponse',
            name='sichtung_locked',
            field=models.BooleanField(default=False, verbose_name='Sichtung gesperrt'),
        ),
        migrations.AddField(
            model_name='victimprofileresponse',
            name='therapie_locked',
            field=models.BooleanField(default=False, verbose_name='Therapie gesperrt'),
        ),
    ]
