# Generated by Django 4.2.28 on 2026-03-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0058_victimprofileresponse_diagnostik_locked_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='victimprofileresponse',
            unique_together={('button_number', 'observer_email')},
        ),
    ]
