# Generated by Django 5.2.17 on 2026-09-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DUEBapp', '0061_hash_observer_passwords'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='victimprofileresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='image_metadata',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formresponse_records', to='DUEBapp.observeraccount'),
        ),
        migrations.AddField(
            model_name='observeraccount',
            name='data_revision',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='observeraccount',
            name='token_created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='victimprofileresponse',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victimprofileresponse_records', to='DUEBapp.observeraccount'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='email_text',
            field=models.TextField(default='Sehr geehrte(r) {name},\n\nhiermit erhalten Sie Ihre Zugangsdaten für die digitale Übungsbeobachtung (DUEB):\n\nBenutzername: {username}\nPasswort: {password}\n\nBitte melden Sie sich unter folgendem Link an:\n{login_url}\n\nIhre erhobenen Daten sind über das Webportal abrufbar. Bitte melden Sie sich unter dem oben genannten Link an.\n\nMit freundlichen Grüßen,\nIhr DUEB-Team', verbose_name='E-Mail-Text'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='subject',
            field=models.CharField(default='Zugangsdaten für die DUEB-Übung', max_length=100, verbose_name='Betreff'),
        ),
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('digest', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DUEBapp.observeraccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('observer', 'request_id'), name='unique_observer_submission')],
            },
        ),
    ]
