# Generated by Django 5.2.17 on 2026-09-09 22:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


def check_existing_data(apps, schema_editor):
    alias = schema_editor.connection.alias
    if apps.get_model("DUEBapp", "TestScenario").objects.using(alias).count() > 1:
        raise RuntimeError(
            "Mehrere aktive Übungen gefunden. Vor dem Upgrade bereinigen und sichern."
        )
    for name, field in [("FormResponse", "form"), ("VictimProfileResponse", "button_number")]:
        duplicate = (
            apps.get_model("DUEBapp", name)
            .objects.using(alias)
            .filter(observer__isnull=False, test_scenario__isnull=False)
            .values("observer", "test_scenario", field)
            .annotate(total=models.Count("pk"))
            .filter(total__gt=1)
            .exists()
        )
        if duplicate:
            raise RuntimeError(
                f"Doppelte {name}-Datensätze gefunden. Vor dem Upgrade fachlich abgleichen; es wird nichts automatisch gelöscht."
            )


def preserve_existing_data(apps, schema_editor):
    alias = schema_editor.connection.alias
    for name in ("ObserverAccount", "TestScenario"):
        model = apps.get_model("DUEBapp", name)
        for obj in model.objects.using(alias).all().iterator():
            model.objects.using(alias).filter(pk=obj.pk).update(public_id=uuid.uuid4())
    scenarios = dict(
        apps.get_model("DUEBapp", "TestScenario")
        .objects.using(alias)
        .values_list("pk", "public_id")
    )
    for name in ("FormResponse", "VictimProfileResponse"):
        model = apps.get_model("DUEBapp", name)
        for scenario_id, public_id in scenarios.items():
            model.objects.using(alias).filter(test_scenario_id=scenario_id).update(
                scenario_uuid=public_id
            )
    image_model = apps.get_model("DUEBapp", "FormResponseImage")
    question_model = apps.get_model("DUEBapp", "Question")
    for response in apps.get_model("DUEBapp", "FormResponse").objects.using(alias).all().iterator():
        metadata = response.image_metadata if isinstance(response.image_metadata, list) else []
        metadata = {entry.get("field"): entry for entry in metadata if isinstance(entry, dict)}
        question_ids = set(
            question_model.objects.using(alias)
            .filter(form_id=response.form_id)
            .values_list("pk", flat=True)
        )
        for index in range(1, 16):
            field = f"image_{index}"
            image = getattr(response, field)
            if not image:
                continue
            info = metadata.get(field, {})
            key = str(info.get("questionId", ""))[:50]
            question_id = int(key) if key.isdecimal() and int(key) in question_ids else None
            image_model.objects.using(alias).create(
                response_id=response.pk,
                question_id=question_id,
                question_key=key,
                image=image.name,
                name=str(info.get("name", ""))[:150],
                position=index,
            )
    # Resolve deferred foreign keys before the subsequent schema changes.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):
    dependencies = [
        ("DUEBapp", "0064_protect_patient_overviews"),
        ("authtoken", "0004_alter_tokenproxy_options"),
    ]

    operations = [
        migrations.RunPython(check_existing_data, migrations.RunPython.noop),
        migrations.CreateModel(
            name="AdminTokenBinding",
            fields=[
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="authtoken.token",
                    ),
                ),
                ("auth_hash", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="FormResponseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_key", models.CharField(blank=True, max_length=50)),
                ("image", models.ImageField(upload_to="uploads/")),
                ("name", models.CharField(blank=True, max_length=150)),
                ("position", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="LoginBucket",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="ObserverEmailDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("batch_id", models.UUIDField()),
                ("subject", models.CharField(max_length=100)),
                ("template", models.TextField()),
                ("recipient", models.EmailField(max_length=254)),
                ("login_url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("sending", "In Zustellung"),
                            ("sent", "Gesendet"),
                            ("failed", "Fehlgeschlagen"),
                            ("uncertain", "Zustellung unklar"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "E-Mail-Versandauftrag",
                "verbose_name_plural": "E-Mail-Versandaufträge",
            },
        ),
        migrations.AddField(
            model_name="formresponse",
            name="scenario_uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="formresponse",
            name="template_snapshot",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="formresponse",
            name="template_version",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="observeraccount",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="testscenario",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="testscenario",
            name="singleton",
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="victimprofileresponse",
            name="scenario_uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="victimprofileresponse",
            name="template_snapshot",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="victimprofileresponse",
            name="template_version",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="formresponseimage",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="DUEBapp.question",
            ),
        ),
        migrations.AddField(
            model_name="formresponseimage",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="DUEBapp.formresponse",
            ),
        ),
        migrations.AddField(
            model_name="observeremaildelivery",
            name="observer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DUEBapp.observeraccount"
            ),
        ),
        migrations.RunPython(preserve_existing_data),
        migrations.AlterField(
            model_name="observeraccount",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="testscenario",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="completedform",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="completedform",
            name="form",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_1",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_10",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_11",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_12",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_13",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_14",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_15",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_2",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_3",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_4",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_5",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_6",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_7",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_8",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_9",
        ),
        migrations.RemoveField(
            model_name="formresponse",
            name="image_metadata",
        ),
        migrations.AddConstraint(
            model_name="formresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("observer__isnull", False), ("test_scenario__isnull", False)),
                fields=("observer", "test_scenario", "form"),
                name="unique_observer_scenario_form",
            ),
        ),
        migrations.AddConstraint(
            model_name="testscenario",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton", 1)), name="one_active_scenario"
            ),
        ),
        migrations.AddConstraint(
            model_name="victimprofileresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("observer__isnull", False), ("test_scenario__isnull", False)),
                fields=("observer", "test_scenario", "button_number"),
                name="unique_observer_scenario_patient",
            ),
        ),
        migrations.DeleteModel(
            name="CompletedForm",
        ),
        migrations.AddConstraint(
            model_name="formresponseimage",
            constraint=models.UniqueConstraint(
                fields=("response", "position"), name="unique_response_image_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="observeremaildelivery",
            constraint=models.UniqueConstraint(
                fields=("observer", "batch_id"), name="unique_observer_mail_batch"
            ),
        ),
    ]
